spring:
  application:
    name: config
  cloud:
     config:
      server:
        git:
          uri: https://gitee.com/jiayuan1234/config-repo
          username: 2352840798@qq.com
          password: zx111111
          basedir: D:\MyData\workspace\IDEA\SpringCloud_Sell\config\basedir
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8082